// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    [Migration("20241203203857_v4")]
    partial class v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("server.Models.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionId"));

                    b.Property<int>("AuctioneerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuctionId");

                    b.HasIndex("AuctioneerId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("server.Models.AuctionResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId1")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId1");

                    b.HasIndex("WinningTeamId");

                    b.ToTable("AuctionResults");
                });

            modelBuilder.Entity("server.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("BidId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("server.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("Bonuses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("server.Models.Finance", b =>
                {
                    b.Property<int>("FinanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinanceId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FinanceId");

                    b.HasIndex("TeamId");

                    b.ToTable("Finances");
                });

            modelBuilder.Entity("server.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("server.Models.PerformanceReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("AnalystId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stats1")
                        .HasColumnType("int");

                    b.Property<int>("Stats2")
                        .HasColumnType("int");

                    b.Property<int>("Stats3")
                        .HasColumnType("int");

                    b.Property<int>("Stats4")
                        .HasColumnType("int");

                    b.Property<string>("Tournament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("AnalystId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PerformanceReports");
                });

            modelBuilder.Entity("server.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("AgentId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Age = 34,
                            AgentId = 1,
                            BasePrice = 200000m,
                            Country = "India",
                            Name = "Virat Kohli",
                            Position = "Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 2,
                            Age = 36,
                            AgentId = 2,
                            BasePrice = 180000m,
                            Country = "India",
                            Name = "Rohit Sharma",
                            Position = "Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 3,
                            Age = 33,
                            AgentId = 3,
                            BasePrice = 190000m,
                            Country = "Australia",
                            Name = "Steve Smith",
                            Position = "Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 4,
                            Age = 33,
                            AgentId = 4,
                            BasePrice = 185000m,
                            Country = "New Zealand",
                            Name = "Kane Williamson",
                            Position = "Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 5,
                            Age = 30,
                            AgentId = 5,
                            BasePrice = 150000m,
                            Country = "India",
                            Name = "Jasprit Bumrah",
                            Position = "Bowler",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 6,
                            Age = 33,
                            AgentId = 1,
                            BasePrice = 160000m,
                            Country = "Australia",
                            Name = "Mitchell Starc",
                            Position = "Bowler",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 7,
                            Age = 34,
                            AgentId = 2,
                            BasePrice = 155000m,
                            Country = "New Zealand",
                            Name = "Trent Boult",
                            Position = "Bowler",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 8,
                            Age = 25,
                            AgentId = 3,
                            BasePrice = 140000m,
                            Country = "Afghanistan",
                            Name = "Rashid Khan",
                            Position = "Bowler",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 9,
                            Age = 32,
                            AgentId = 4,
                            BasePrice = 175000m,
                            Country = "England",
                            Name = "Jos Buttler",
                            Position = "Wicketkeeper-Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 10,
                            Age = 41,
                            AgentId = 5,
                            BasePrice = 190000m,
                            Country = "India",
                            Name = "MS Dhoni",
                            Position = "Wicketkeeper-Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 11,
                            Age = 32,
                            AgentId = 1,
                            BasePrice = 200000m,
                            Country = "England",
                            Name = "Ben Stokes",
                            Position = "All-Rounder",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 12,
                            Age = 35,
                            AgentId = 2,
                            BasePrice = 180000m,
                            Country = "India",
                            Name = "Ravindra Jadeja",
                            Position = "All-Rounder",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 13,
                            Age = 30,
                            AgentId = 3,
                            BasePrice = 170000m,
                            Country = "Australia",
                            Name = "Pat Cummins",
                            Position = "All-Rounder",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 14,
                            Age = 36,
                            AgentId = 4,
                            BasePrice = 300000m,
                            Country = "Argentina",
                            Name = "Lionel Messi",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 15,
                            Age = 38,
                            AgentId = 5,
                            BasePrice = 290000m,
                            Country = "Portugal",
                            Name = "Cristiano Ronaldo",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 16,
                            Age = 31,
                            AgentId = 1,
                            BasePrice = 280000m,
                            Country = "Brazil",
                            Name = "Neymar Jr.",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 17,
                            Age = 32,
                            AgentId = 2,
                            BasePrice = 270000m,
                            Country = "Belgium",
                            Name = "Kevin De Bruyne",
                            Position = "Midfielder",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 18,
                            Age = 25,
                            AgentId = 3,
                            BasePrice = 295000m,
                            Country = "France",
                            Name = "Kylian Mbappé",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 19,
                            Age = 35,
                            AgentId = 4,
                            BasePrice = 280000m,
                            Country = "Poland",
                            Name = "Robert Lewandowski",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 20,
                            Age = 23,
                            AgentId = 5,
                            BasePrice = 320000m,
                            Country = "Norway",
                            Name = "Erling Haaland",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 21,
                            Age = 38,
                            AgentId = 1,
                            BasePrice = 250000m,
                            Country = "Croatia",
                            Name = "Luka Modrić",
                            Position = "Midfielder",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 22,
                            Age = 32,
                            AgentId = 2,
                            BasePrice = 270000m,
                            Country = "Netherlands",
                            Name = "Virgil van Dijk",
                            Position = "Defender",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 23,
                            Age = 21,
                            AgentId = 3,
                            BasePrice = 240000m,
                            Country = "Spain",
                            Name = "Pedri González",
                            Position = "Midfielder",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 24,
                            Age = 22,
                            AgentId = 4,
                            BasePrice = 250000m,
                            Country = "England",
                            Name = "Cole Palmer",
                            Position = "Midfielder",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 25,
                            Age = 24,
                            AgentId = 5,
                            BasePrice = 300000m,
                            Country = "Brazil",
                            Name = "Vinicious Junior",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RosterSize")
                        .HasColumnType("int");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TeamId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Budget = 1600000m,
                            ManagerId = 6,
                            Name = "Chennai Super Kings",
                            Region = "India",
                            RosterSize = 0,
                            Sport = "Cricket",
                            TotalExpenditure = 0m
                        },
                        new
                        {
                            TeamId = 2,
                            Budget = 1750000m,
                            ManagerId = 7,
                            Name = "Royal Challengers Bangalore",
                            Region = "India",
                            RosterSize = 0,
                            Sport = "Cricket",
                            TotalExpenditure = 0m
                        },
                        new
                        {
                            TeamId = 3,
                            Budget = 1550000m,
                            ManagerId = 8,
                            Name = "Mumbai Indians",
                            Region = "India",
                            RosterSize = 0,
                            Sport = "Cricket",
                            TotalExpenditure = 0m
                        },
                        new
                        {
                            TeamId = 4,
                            Budget = 1600000m,
                            ManagerId = 9,
                            Name = "Real Madrid",
                            Region = "Spain",
                            RosterSize = 0,
                            Sport = "Football",
                            TotalExpenditure = 0m
                        },
                        new
                        {
                            TeamId = 5,
                            Budget = 1650000m,
                            ManagerId = 10,
                            Name = "Manchester City",
                            Region = "England",
                            RosterSize = 0,
                            Sport = "Football",
                            TotalExpenditure = 0m
                        });
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "davidagent@gmail.com",
                            IsActive = true,
                            Password = "$2a$10$f8g/nLj9O/SibpWRhz3GjOJe4zXPvkGkz7k609g7BZXyntrcOP5By",
                            Role = "Player Agent",
                            Username = "David Agent"
                        });
                });

            modelBuilder.Entity("server.Models.Auction", b =>
                {
                    b.HasOne("server.Models.User", "Auctioneer")
                        .WithMany("Auctions")
                        .HasForeignKey("AuctioneerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auctioneer");
                });

            modelBuilder.Entity("server.Models.AuctionResult", b =>
                {
                    b.HasOne("server.Models.Auction", "Auction")
                        .WithMany("AuctionResults")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Player", null)
                        .WithMany("AuctionResults")
                        .HasForeignKey("PlayerId1");

                    b.HasOne("server.Models.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("WinningTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Auction");

                    b.Navigation("Player");

                    b.Navigation("WinningTeam");
                });

            modelBuilder.Entity("server.Models.Bid", b =>
                {
                    b.HasOne("server.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Team", "Team")
                        .WithMany("Bids")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("server.Models.Contract", b =>
                {
                    b.HasOne("server.Models.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("server.Models.Finance", b =>
                {
                    b.HasOne("server.Models.Team", "Team")
                        .WithMany("Finances")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("server.Models.Notification", b =>
                {
                    b.HasOne("server.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.PerformanceReport", b =>
                {
                    b.HasOne("server.Models.User", "Analyst")
                        .WithMany("PerformanceReports")
                        .HasForeignKey("AnalystId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Player", "Player")
                        .WithMany("PerformanceReports")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analyst");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("server.Models.Player", b =>
                {
                    b.HasOne("server.Models.User", "Agent")
                        .WithMany("Players")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.HasOne("server.Models.User", "Manager")
                        .WithMany("ManagedTeams")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("server.Models.Auction", b =>
                {
                    b.Navigation("AuctionResults");

                    b.Navigation("Bids");
                });

            modelBuilder.Entity("server.Models.Player", b =>
                {
                    b.Navigation("AuctionResults");

                    b.Navigation("Contracts");

                    b.Navigation("PerformanceReports");
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Finances");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("ManagedTeams");

                    b.Navigation("Notifications");

                    b.Navigation("PerformanceReports");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
