// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Data;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    [Migration("20241204223142_v9")]
    partial class v9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("server.Models.Auction", b =>
                {
                    b.Property<int>("AuctionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuctionId"));

                    b.Property<int>("AuctioneerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuctionId");

                    b.HasIndex("AuctioneerId");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("server.Models.AuctionResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId1")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WinningTeamId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId1");

                    b.HasIndex("WinningTeamId");

                    b.ToTable("AuctionResults");
                });

            modelBuilder.Entity("server.Models.Bid", b =>
                {
                    b.Property<int>("BidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BidId"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("BidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("BidId");

                    b.HasIndex("AuctionId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("server.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("Bonuses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("server.Models.Finance", b =>
                {
                    b.Property<int>("FinanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinanceId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FinanceId");

                    b.HasIndex("TeamId");

                    b.ToTable("Finances");
                });

            modelBuilder.Entity("server.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("server.Models.PerformanceReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("AnalystId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opponent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stats1")
                        .HasColumnType("int");

                    b.Property<int>("Stats2")
                        .HasColumnType("int");

                    b.Property<int>("Stats3")
                        .HasColumnType("int");

                    b.Property<int>("Stats4")
                        .HasColumnType("int");

                    b.Property<string>("Tournament")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("AnalystId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PerformanceReports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Royal Challengers Bangalore",
                            PlayerId = 1,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 75,
                            Stats2 = 45,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "IPL"
                        },
                        new
                        {
                            ReportId = 2,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Australia",
                            PlayerId = 1,
                            Rating = 9.1999999999999993,
                            Sport = "Cricket",
                            Stats1 = 110,
                            Stats2 = 95,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 3,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "England",
                            PlayerId = 1,
                            Rating = 8.0,
                            Sport = "Cricket",
                            Stats1 = 85,
                            Stats2 = 180,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 4,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Mumbai Indians",
                            PlayerId = 2,
                            Rating = 7.7999999999999998,
                            Sport = "Cricket",
                            Stats1 = 65,
                            Stats2 = 40,
                            Stats3 = 1,
                            Stats4 = 12,
                            Tournament = "Domestic League"
                        },
                        new
                        {
                            ReportId = 5,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "New Zealand",
                            PlayerId = 2,
                            Rating = 8.6999999999999993,
                            Sport = "Cricket",
                            Stats1 = 95,
                            Stats2 = 80,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 6,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "South Africa",
                            PlayerId = 2,
                            Rating = 7.5,
                            Sport = "Cricket",
                            Stats1 = 70,
                            Stats2 = 150,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 7,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Sydney Sixers",
                            PlayerId = 3,
                            Rating = 7.5,
                            Sport = "Cricket",
                            Stats1 = 55,
                            Stats2 = 35,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "Big Bash League"
                        },
                        new
                        {
                            ReportId = 8,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "India",
                            PlayerId = 3,
                            Rating = 8.3000000000000007,
                            Sport = "Cricket",
                            Stats1 = 80,
                            Stats2 = 70,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 9,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "West Indies",
                            PlayerId = 3,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 90,
                            Stats2 = 200,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 10,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Auckland Aces",
                            PlayerId = 4,
                            Rating = 8.0,
                            Sport = "Cricket",
                            Stats1 = 60,
                            Stats2 = 45,
                            Stats3 = 1,
                            Stats4 = 12,
                            Tournament = "Super Smash"
                        },
                        new
                        {
                            ReportId = 11,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Pakistan",
                            PlayerId = 4,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 85,
                            Stats2 = 75,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 12,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "Bangladesh",
                            PlayerId = 4,
                            Rating = 7.7999999999999998,
                            Sport = "Cricket",
                            Stats1 = 75,
                            Stats2 = 180,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 13,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Chennai Super Kings",
                            PlayerId = 5,
                            Rating = 8.6999999999999993,
                            Sport = "Cricket",
                            Stats1 = 15,
                            Stats2 = 10,
                            Stats3 = 3,
                            Stats4 = 24,
                            Tournament = "IPL"
                        },
                        new
                        {
                            ReportId = 14,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Sri Lanka",
                            PlayerId = 5,
                            Rating = 9.0,
                            Sport = "Cricket",
                            Stats1 = 10,
                            Stats2 = 8,
                            Stats3 = 2,
                            Stats4 = 60,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 15,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "England",
                            PlayerId = 5,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 20,
                            Stats2 = 15,
                            Stats3 = 4,
                            Stats4 = 120,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 16,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Sydney Thunder",
                            PlayerId = 6,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 20,
                            Stats2 = 15,
                            Stats3 = 4,
                            Stats4 = 24,
                            Tournament = "Big Bash League"
                        },
                        new
                        {
                            ReportId = 17,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "India",
                            PlayerId = 6,
                            Rating = 8.6999999999999993,
                            Sport = "Cricket",
                            Stats1 = 15,
                            Stats2 = 10,
                            Stats3 = 3,
                            Stats4 = 60,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 18,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "England",
                            PlayerId = 6,
                            Rating = 9.0,
                            Sport = "Cricket",
                            Stats1 = 25,
                            Stats2 = 20,
                            Stats3 = 5,
                            Stats4 = 120,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 19,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Canterbury Kings",
                            PlayerId = 7,
                            Rating = 8.0,
                            Sport = "Cricket",
                            Stats1 = 15,
                            Stats2 = 12,
                            Stats3 = 3,
                            Stats4 = 24,
                            Tournament = "Super Smash"
                        },
                        new
                        {
                            ReportId = 20,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Pakistan",
                            PlayerId = 7,
                            Rating = 8.3000000000000007,
                            Sport = "Cricket",
                            Stats1 = 10,
                            Stats2 = 8,
                            Stats3 = 2,
                            Stats4 = 55,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 21,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "South Africa",
                            PlayerId = 7,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 20,
                            Stats2 = 15,
                            Stats3 = 4,
                            Stats4 = 110,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 22,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Kabul Zwanan",
                            PlayerId = 8,
                            Rating = 8.6999999999999993,
                            Sport = "Cricket",
                            Stats1 = 35,
                            Stats2 = 25,
                            Stats3 = 3,
                            Stats4 = 24,
                            Tournament = "Afghanistan Premier League"
                        },
                        new
                        {
                            ReportId = 23,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Sri Lanka",
                            PlayerId = 8,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 25,
                            Stats2 = 20,
                            Stats3 = 2,
                            Stats4 = 48,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 24,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "Bangladesh",
                            PlayerId = 8,
                            Rating = 9.0,
                            Sport = "Cricket",
                            Stats1 = 40,
                            Stats2 = 30,
                            Stats3 = 4,
                            Stats4 = 96,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 25,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Rajasthan Royals",
                            PlayerId = 9,
                            Rating = 8.8000000000000007,
                            Sport = "Cricket",
                            Stats1 = 80,
                            Stats2 = 50,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "IPL"
                        },
                        new
                        {
                            ReportId = 26,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Australia",
                            PlayerId = 9,
                            Rating = 9.1999999999999993,
                            Sport = "Cricket",
                            Stats1 = 105,
                            Stats2 = 85,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 27,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "West Indies",
                            PlayerId = 9,
                            Rating = 8.0,
                            Sport = "Cricket",
                            Stats1 = 75,
                            Stats2 = 160,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 28,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Chennai Super Kings",
                            PlayerId = 10,
                            Rating = 8.3000000000000007,
                            Sport = "Cricket",
                            Stats1 = 50,
                            Stats2 = 35,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "IPL"
                        },
                        new
                        {
                            ReportId = 29,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Mumbai Indians",
                            PlayerId = 10,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 65,
                            Stats2 = 55,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "Domestic Match"
                        },
                        new
                        {
                            ReportId = 30,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "India Maharajas",
                            PlayerId = 10,
                            Rating = 8.0,
                            Sport = "Cricket",
                            Stats1 = 45,
                            Stats2 = 30,
                            Stats3 = 0,
                            Stats4 = 0,
                            Tournament = "Legends League"
                        },
                        new
                        {
                            ReportId = 31,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Manchester Originals",
                            PlayerId = 11,
                            Rating = 9.0,
                            Sport = "Cricket",
                            Stats1 = 65,
                            Stats2 = 40,
                            Stats3 = 3,
                            Stats4 = 24,
                            Tournament = "The Hundred"
                        },
                        new
                        {
                            ReportId = 32,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Australia",
                            PlayerId = 11,
                            Rating = 9.1999999999999993,
                            Sport = "Cricket",
                            Stats1 = 85,
                            Stats2 = 70,
                            Stats3 = 2,
                            Stats4 = 48,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 33,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "India",
                            PlayerId = 11,
                            Rating = 8.8000000000000007,
                            Sport = "Cricket",
                            Stats1 = 75,
                            Stats2 = 160,
                            Stats3 = 4,
                            Stats4 = 120,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 34,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Chennai Super Kings",
                            PlayerId = 12,
                            Rating = 8.5,
                            Sport = "Cricket",
                            Stats1 = 45,
                            Stats2 = 30,
                            Stats3 = 2,
                            Stats4 = 24,
                            Tournament = "IPL"
                        },
                        new
                        {
                            ReportId = 35,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "Pakistan",
                            PlayerId = 12,
                            Rating = 8.6999999999999993,
                            Sport = "Cricket",
                            Stats1 = 55,
                            Stats2 = 40,
                            Stats3 = 3,
                            Stats4 = 48,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 36,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "England",
                            PlayerId = 12,
                            Rating = 8.3000000000000007,
                            Sport = "Cricket",
                            Stats1 = 40,
                            Stats2 = 80,
                            Stats3 = 4,
                            Stats4 = 96,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 37,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "T20",
                            Opponent = "Sydney Sixers",
                            PlayerId = 13,
                            Rating = 8.5999999999999996,
                            Sport = "Cricket",
                            Stats1 = 25,
                            Stats2 = 15,
                            Stats3 = 4,
                            Stats4 = 24,
                            Tournament = "Big Bash League"
                        },
                        new
                        {
                            ReportId = 38,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "ODI",
                            Opponent = "New Zealand",
                            PlayerId = 13,
                            Rating = 8.8000000000000007,
                            Sport = "Cricket",
                            Stats1 = 35,
                            Stats2 = 25,
                            Stats3 = 3,
                            Stats4 = 60,
                            Tournament = "World Cup"
                        },
                        new
                        {
                            ReportId = 39,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Test",
                            Opponent = "South Africa",
                            PlayerId = 13,
                            Rating = 9.0,
                            Sport = "Cricket",
                            Stats1 = 40,
                            Stats2 = 30,
                            Stats3 = 5,
                            Stats4 = 120,
                            Tournament = "Test Series"
                        },
                        new
                        {
                            ReportId = 40,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Inter Miami",
                            PlayerId = 14,
                            Rating = 9.0,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 1,
                            Stats3 = 35,
                            Stats4 = 2,
                            Tournament = "Leagues Cup"
                        },
                        new
                        {
                            ReportId = 41,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "International",
                            Opponent = "Brazil",
                            PlayerId = 14,
                            Rating = 8.6999999999999993,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 45,
                            Stats4 = 1,
                            Tournament = "Coppa America"
                        },
                        new
                        {
                            ReportId = 42,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Real Madrid",
                            PlayerId = 14,
                            Rating = 8.5,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 40,
                            Stats4 = 3,
                            Tournament = "Champions League"
                        },
                        new
                        {
                            ReportId = 43,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Al Nassr",
                            PlayerId = 15,
                            Rating = 8.8000000000000007,
                            Sport = "Football",
                            Stats1 = 3,
                            Stats2 = 0,
                            Stats3 = 25,
                            Stats4 = 1,
                            Tournament = "Saudi Pro League"
                        },
                        new
                        {
                            ReportId = 44,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "International Cup",
                            Opponent = "Al Hilal",
                            PlayerId = 15,
                            Rating = 9.0,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 1,
                            Stats3 = 30,
                            Stats4 = 2,
                            Tournament = "Club World Cup"
                        },
                        new
                        {
                            ReportId = 45,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Al Ittihad",
                            PlayerId = 15,
                            Rating = 8.5,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 35,
                            Stats4 = 1,
                            Tournament = "Saudi Pro League"
                        },
                        new
                        {
                            ReportId = 46,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Paris Saint-Germain",
                            PlayerId = 16,
                            Rating = 8.6999999999999993,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 1,
                            Stats3 = 40,
                            Stats4 = 2,
                            Tournament = "Ligue 1"
                        },
                        new
                        {
                            ReportId = 47,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "International Cup",
                            Opponent = "Flamengo",
                            PlayerId = 16,
                            Rating = 8.5,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 45,
                            Stats4 = 1,
                            Tournament = "Copa Libertadores"
                        },
                        new
                        {
                            ReportId = 48,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Barcelona",
                            PlayerId = 16,
                            Rating = 8.3000000000000007,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 38,
                            Stats4 = 3,
                            Tournament = "Champions League"
                        },
                        new
                        {
                            ReportId = 49,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Manchester City",
                            PlayerId = 17,
                            Rating = 8.9000000000000004,
                            Sport = "Football",
                            Stats1 = 0,
                            Stats2 = 3,
                            Stats3 = 55,
                            Stats4 = 2,
                            Tournament = "Premier League"
                        },
                        new
                        {
                            ReportId = 50,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Chelsea",
                            PlayerId = 17,
                            Rating = 8.6999999999999993,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 48,
                            Stats4 = 1,
                            Tournament = "FA Cup"
                        },
                        new
                        {
                            ReportId = 51,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Real Madrid",
                            PlayerId = 17,
                            Rating = 8.5,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 50,
                            Stats4 = 3,
                            Tournament = "Champions League"
                        },
                        new
                        {
                            ReportId = 52,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Paris Saint-Germain",
                            PlayerId = 18,
                            Rating = 9.0,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 1,
                            Stats3 = 35,
                            Stats4 = 1,
                            Tournament = "Ligue 1"
                        },
                        new
                        {
                            ReportId = 53,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Barcelona",
                            PlayerId = 18,
                            Rating = 8.8000000000000007,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 40,
                            Stats4 = 2,
                            Tournament = "Champions League"
                        },
                        new
                        {
                            ReportId = 54,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Lyon",
                            PlayerId = 18,
                            Rating = 9.1999999999999993,
                            Sport = "Football",
                            Stats1 = 3,
                            Stats2 = 0,
                            Stats3 = 30,
                            Stats4 = 1,
                            Tournament = "Coupe de France"
                        },
                        new
                        {
                            ReportId = 55,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Barcelona",
                            PlayerId = 19,
                            Rating = 8.5999999999999996,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 1,
                            Stats3 = 25,
                            Stats4 = 1,
                            Tournament = "La Liga"
                        },
                        new
                        {
                            ReportId = 56,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Real Madrid",
                            PlayerId = 19,
                            Rating = 8.4000000000000004,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 30,
                            Stats4 = 2,
                            Tournament = "Copa del Rey"
                        },
                        new
                        {
                            ReportId = 57,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Manchester City",
                            PlayerId = 19,
                            Rating = 8.5,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 28,
                            Stats4 = 1,
                            Tournament = "Champions League"
                        },
                        new
                        {
                            ReportId = 58,
                            AnalystId = 11,
                            MatchDate = new DateTime(2024, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Manchester United",
                            PlayerId = 20,
                            Rating = 9.3000000000000007,
                            Sport = "Football",
                            Stats1 = 3,
                            Stats2 = 0,
                            Stats3 = 20,
                            Stats4 = 1,
                            Tournament = "Premier League"
                        },
                        new
                        {
                            ReportId = 59,
                            AnalystId = 12,
                            MatchDate = new DateTime(2024, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Chelsea",
                            PlayerId = 20,
                            Rating = 9.0999999999999996,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 1,
                            Stats3 = 25,
                            Stats4 = 2,
                            Tournament = "FA Cup"
                        },
                        new
                        {
                            ReportId = 60,
                            AnalystId = 13,
                            MatchDate = new DateTime(2024, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Cup",
                            Opponent = "Real Madrid",
                            PlayerId = 20,
                            Rating = 8.9000000000000004,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 30,
                            Stats4 = 1,
                            Tournament = "Champions League"
                        },
                        new
                        {
                            ReportId = 70,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Knockout",
                            Opponent = "Real Madrid",
                            PlayerId = 21,
                            Rating = 8.5,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 50,
                            Stats4 = 3,
                            Tournament = "UEFA Champions League"
                        },
                        new
                        {
                            ReportId = 71,
                            AnalystId = 12,
                            MatchDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Barcelona",
                            PlayerId = 21,
                            Rating = 7.7999999999999998,
                            Sport = "Football",
                            Stats1 = 0,
                            Stats2 = 1,
                            Stats3 = 45,
                            Stats4 = 4,
                            Tournament = "La Liga"
                        },
                        new
                        {
                            ReportId = 72,
                            AnalystId = 13,
                            MatchDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Semifinal",
                            Opponent = "Atletico Madrid",
                            PlayerId = 21,
                            Rating = 8.3000000000000007,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 55,
                            Stats4 = 2,
                            Tournament = "Copa del Rey"
                        },
                        new
                        {
                            ReportId = 73,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Sevilla",
                            PlayerId = 21,
                            Rating = 9.0,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 0,
                            Stats3 = 60,
                            Stats4 = 5,
                            Tournament = "La Liga"
                        },
                        new
                        {
                            ReportId = 74,
                            AnalystId = 12,
                            MatchDate = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Final",
                            Opponent = "Chelsea",
                            PlayerId = 21,
                            Rating = 8.6999999999999993,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 48,
                            Stats4 = 3,
                            Tournament = "UEFA Super Cup"
                        },
                        new
                        {
                            ReportId = 75,
                            AnalystId = 13,
                            MatchDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Manchester United",
                            PlayerId = 22,
                            Rating = 8.5,
                            Sport = "Football",
                            Stats1 = 0,
                            Stats2 = 0,
                            Stats3 = 40,
                            Stats4 = 10,
                            Tournament = "Premier League"
                        },
                        new
                        {
                            ReportId = 76,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Knockout",
                            Opponent = "Real Madrid",
                            PlayerId = 22,
                            Rating = 8.1999999999999993,
                            Sport = "Football",
                            Stats1 = 0,
                            Stats2 = 0,
                            Stats3 = 42,
                            Stats4 = 9,
                            Tournament = "UEFA Champions League"
                        },
                        new
                        {
                            ReportId = 77,
                            AnalystId = 12,
                            MatchDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Quarterfinal",
                            Opponent = "Chelsea",
                            PlayerId = 22,
                            Rating = 8.6999999999999993,
                            Sport = "Football",
                            Stats1 = 0,
                            Stats2 = 0,
                            Stats3 = 45,
                            Stats4 = 12,
                            Tournament = "FA Cup"
                        },
                        new
                        {
                            ReportId = 78,
                            AnalystId = 13,
                            MatchDate = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Tottenham",
                            PlayerId = 22,
                            Rating = 9.0,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 0,
                            Stats3 = 50,
                            Stats4 = 8,
                            Tournament = "Premier League"
                        },
                        new
                        {
                            ReportId = 79,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Final",
                            Opponent = "Sevilla",
                            PlayerId = 22,
                            Rating = 8.8000000000000007,
                            Sport = "Football",
                            Stats1 = 0,
                            Stats2 = 0,
                            Stats3 = 55,
                            Stats4 = 7,
                            Tournament = "UEFA Europa League"
                        },
                        new
                        {
                            ReportId = 80,
                            AnalystId = 12,
                            MatchDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Real Madrid",
                            PlayerId = 23,
                            Rating = 8.4000000000000004,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 3,
                            Stats3 = 50,
                            Stats4 = 2,
                            Tournament = "La Liga"
                        },
                        new
                        {
                            ReportId = 81,
                            AnalystId = 13,
                            MatchDate = new DateTime(2023, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Semifinal",
                            Opponent = "Atletico Madrid",
                            PlayerId = 23,
                            Rating = 8.0999999999999996,
                            Sport = "Football",
                            Stats1 = 0,
                            Stats2 = 2,
                            Stats3 = 40,
                            Stats4 = 3,
                            Tournament = "Copa del Rey"
                        },
                        new
                        {
                            ReportId = 82,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Quarterfinal",
                            Opponent = "Bayern Munich",
                            PlayerId = 23,
                            Rating = 8.5999999999999996,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 48,
                            Stats4 = 2,
                            Tournament = "UEFA Champions League"
                        },
                        new
                        {
                            ReportId = 83,
                            AnalystId = 12,
                            MatchDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Valencia",
                            PlayerId = 23,
                            Rating = 9.0,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 0,
                            Stats3 = 55,
                            Stats4 = 1,
                            Tournament = "La Liga"
                        },
                        new
                        {
                            ReportId = 84,
                            AnalystId = 13,
                            MatchDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Final",
                            Opponent = "Inter Milan",
                            PlayerId = 23,
                            Rating = 8.9000000000000004,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 47,
                            Stats4 = 2,
                            Tournament = "UEFA Super Cup"
                        },
                        new
                        {
                            ReportId = 85,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Manchester United",
                            PlayerId = 24,
                            Rating = 8.8000000000000007,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 1,
                            Stats3 = 35,
                            Stats4 = 5,
                            Tournament = "Premier League"
                        },
                        new
                        {
                            ReportId = 86,
                            AnalystId = 12,
                            MatchDate = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Semifinal",
                            Opponent = "Liverpool",
                            PlayerId = 24,
                            Rating = 8.5,
                            Sport = "Football",
                            Stats1 = 0,
                            Stats2 = 3,
                            Stats3 = 40,
                            Stats4 = 4,
                            Tournament = "FA Cup"
                        },
                        new
                        {
                            ReportId = 87,
                            AnalystId = 13,
                            MatchDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Final",
                            Opponent = "Arsenal",
                            PlayerId = 24,
                            Rating = 8.6999999999999993,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 42,
                            Stats4 = 3,
                            Tournament = "Carabao Cup"
                        },
                        new
                        {
                            ReportId = 88,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Chelsea",
                            PlayerId = 24,
                            Rating = 9.0999999999999996,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 1,
                            Stats3 = 45,
                            Stats4 = 2,
                            Tournament = "Premier League"
                        },
                        new
                        {
                            ReportId = 89,
                            AnalystId = 12,
                            MatchDate = new DateTime(2023, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Final",
                            Opponent = "Sevilla",
                            PlayerId = 24,
                            Rating = 8.9000000000000004,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 2,
                            Stats3 = 50,
                            Stats4 = 1,
                            Tournament = "UEFA Europa League"
                        },
                        new
                        {
                            ReportId = 90,
                            AnalystId = 13,
                            MatchDate = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Barcelona",
                            PlayerId = 25,
                            Rating = 9.3000000000000007,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 0,
                            Stats3 = 60,
                            Stats4 = 2,
                            Tournament = "La Liga"
                        },
                        new
                        {
                            ReportId = 91,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Semifinal",
                            Opponent = "Manchester City",
                            PlayerId = 25,
                            Rating = 8.6999999999999993,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 58,
                            Stats4 = 3,
                            Tournament = "UEFA Champions League"
                        },
                        new
                        {
                            ReportId = 92,
                            AnalystId = 12,
                            MatchDate = new DateTime(2023, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Final",
                            Opponent = "Valencia",
                            PlayerId = 25,
                            Rating = 9.5,
                            Sport = "Football",
                            Stats1 = 2,
                            Stats2 = 2,
                            Stats3 = 62,
                            Stats4 = 4,
                            Tournament = "Copa del Rey"
                        },
                        new
                        {
                            ReportId = 93,
                            AnalystId = 13,
                            MatchDate = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "League",
                            Opponent = "Sevilla",
                            PlayerId = 25,
                            Rating = 8.9000000000000004,
                            Sport = "Football",
                            Stats1 = 1,
                            Stats2 = 1,
                            Stats3 = 54,
                            Stats4 = 2,
                            Tournament = "La Liga"
                        },
                        new
                        {
                            ReportId = 94,
                            AnalystId = 11,
                            MatchDate = new DateTime(2023, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchType = "Final",
                            Opponent = "PSG",
                            PlayerId = 25,
                            Rating = 9.6999999999999993,
                            Sport = "Football",
                            Stats1 = 3,
                            Stats2 = 1,
                            Stats3 = 68,
                            Stats4 = 1,
                            Tournament = "UEFA Super Cup"
                        });
                });

            modelBuilder.Entity("server.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("AgentId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Age = 34,
                            AgentId = 1,
                            BasePrice = 200000m,
                            Country = "India",
                            Name = "Virat Kohli",
                            Position = "Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 2,
                            Age = 36,
                            AgentId = 2,
                            BasePrice = 180000m,
                            Country = "India",
                            Name = "Rohit Sharma",
                            Position = "Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 3,
                            Age = 33,
                            AgentId = 3,
                            BasePrice = 190000m,
                            Country = "Australia",
                            Name = "Steve Smith",
                            Position = "Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 4,
                            Age = 33,
                            AgentId = 4,
                            BasePrice = 185000m,
                            Country = "New Zealand",
                            Name = "Kane Williamson",
                            Position = "Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 5,
                            Age = 30,
                            AgentId = 5,
                            BasePrice = 150000m,
                            Country = "India",
                            Name = "Jasprit Bumrah",
                            Position = "Bowler",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 6,
                            Age = 33,
                            AgentId = 1,
                            BasePrice = 160000m,
                            Country = "Australia",
                            Name = "Mitchell Starc",
                            Position = "Bowler",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 7,
                            Age = 34,
                            AgentId = 2,
                            BasePrice = 155000m,
                            Country = "New Zealand",
                            Name = "Trent Boult",
                            Position = "Bowler",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 8,
                            Age = 25,
                            AgentId = 3,
                            BasePrice = 140000m,
                            Country = "Afghanistan",
                            Name = "Rashid Khan",
                            Position = "Bowler",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 9,
                            Age = 32,
                            AgentId = 4,
                            BasePrice = 175000m,
                            Country = "England",
                            Name = "Jos Buttler",
                            Position = "Wicketkeeper-Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 10,
                            Age = 41,
                            AgentId = 5,
                            BasePrice = 190000m,
                            Country = "India",
                            Name = "MS Dhoni",
                            Position = "Wicketkeeper-Batsman",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 11,
                            Age = 32,
                            AgentId = 1,
                            BasePrice = 200000m,
                            Country = "England",
                            Name = "Ben Stokes",
                            Position = "All-Rounder",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 12,
                            Age = 35,
                            AgentId = 2,
                            BasePrice = 180000m,
                            Country = "India",
                            Name = "Ravindra Jadeja",
                            Position = "All-Rounder",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 13,
                            Age = 30,
                            AgentId = 3,
                            BasePrice = 170000m,
                            Country = "Australia",
                            Name = "Pat Cummins",
                            Position = "All-Rounder",
                            Sport = "Cricket",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 14,
                            Age = 36,
                            AgentId = 4,
                            BasePrice = 300000m,
                            Country = "Argentina",
                            Name = "Lionel Messi",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 15,
                            Age = 38,
                            AgentId = 5,
                            BasePrice = 290000m,
                            Country = "Portugal",
                            Name = "Cristiano Ronaldo",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 16,
                            Age = 31,
                            AgentId = 1,
                            BasePrice = 280000m,
                            Country = "Brazil",
                            Name = "Neymar Jr.",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 17,
                            Age = 32,
                            AgentId = 2,
                            BasePrice = 270000m,
                            Country = "Belgium",
                            Name = "Kevin De Bruyne",
                            Position = "Midfielder",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 18,
                            Age = 25,
                            AgentId = 3,
                            BasePrice = 295000m,
                            Country = "France",
                            Name = "Kylian Mbappé",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 19,
                            Age = 35,
                            AgentId = 4,
                            BasePrice = 280000m,
                            Country = "Poland",
                            Name = "Robert Lewandowski",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 20,
                            Age = 23,
                            AgentId = 5,
                            BasePrice = 320000m,
                            Country = "Norway",
                            Name = "Erling Haaland",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 21,
                            Age = 38,
                            AgentId = 1,
                            BasePrice = 250000m,
                            Country = "Croatia",
                            Name = "Luka Modrić",
                            Position = "Midfielder",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 22,
                            Age = 32,
                            AgentId = 2,
                            BasePrice = 270000m,
                            Country = "Netherlands",
                            Name = "Virgil van Dijk",
                            Position = "Defender",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 23,
                            Age = 21,
                            AgentId = 3,
                            BasePrice = 240000m,
                            Country = "Spain",
                            Name = "Pedri González",
                            Position = "Midfielder",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 24,
                            Age = 22,
                            AgentId = 4,
                            BasePrice = 250000m,
                            Country = "England",
                            Name = "Cole Palmer",
                            Position = "Midfielder",
                            Sport = "Football",
                            Status = "Available"
                        },
                        new
                        {
                            PlayerId = 25,
                            Age = 24,
                            AgentId = 5,
                            BasePrice = 300000m,
                            Country = "Brazil",
                            Name = "Vinicious Junior",
                            Position = "Forward",
                            Sport = "Football",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RosterSize")
                        .HasColumnType("int");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TeamId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            Budget = 1600000m,
                            ManagerId = 6,
                            Name = "Chennai Super Kings",
                            Region = "India",
                            RosterSize = 0,
                            Sport = "Cricket",
                            TotalExpenditure = 0m
                        },
                        new
                        {
                            TeamId = 2,
                            Budget = 1750000m,
                            ManagerId = 7,
                            Name = "Royal Challengers Bangalore",
                            Region = "India",
                            RosterSize = 0,
                            Sport = "Cricket",
                            TotalExpenditure = 0m
                        },
                        new
                        {
                            TeamId = 3,
                            Budget = 1550000m,
                            ManagerId = 8,
                            Name = "Mumbai Indians",
                            Region = "India",
                            RosterSize = 0,
                            Sport = "Cricket",
                            TotalExpenditure = 0m
                        },
                        new
                        {
                            TeamId = 4,
                            Budget = 1600000m,
                            ManagerId = 9,
                            Name = "Real Madrid",
                            Region = "Spain",
                            RosterSize = 0,
                            Sport = "Football",
                            TotalExpenditure = 0m
                        },
                        new
                        {
                            TeamId = 5,
                            Budget = 1650000m,
                            ManagerId = 10,
                            Name = "Manchester City",
                            Region = "England",
                            RosterSize = 0,
                            Sport = "Football",
                            TotalExpenditure = 0m
                        });
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "davidagent@gmail.com",
                            IsActive = true,
                            Password = "$2a$10$f8g/nLj9O/SibpWRhz3GjOJe4zXPvkGkz7k609g7BZXyntrcOP5By",
                            Role = "Player Agent",
                            Username = "David Agent"
                        });
                });

            modelBuilder.Entity("server.Models.Auction", b =>
                {
                    b.HasOne("server.Models.User", "Auctioneer")
                        .WithMany("Auctions")
                        .HasForeignKey("AuctioneerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auctioneer");
                });

            modelBuilder.Entity("server.Models.AuctionResult", b =>
                {
                    b.HasOne("server.Models.Auction", "Auction")
                        .WithMany("AuctionResults")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Player", null)
                        .WithMany("AuctionResults")
                        .HasForeignKey("PlayerId1");

                    b.HasOne("server.Models.Team", "WinningTeam")
                        .WithMany()
                        .HasForeignKey("WinningTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Auction");

                    b.Navigation("Player");

                    b.Navigation("WinningTeam");
                });

            modelBuilder.Entity("server.Models.Bid", b =>
                {
                    b.HasOne("server.Models.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Team", "Team")
                        .WithMany("Bids")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("server.Models.Contract", b =>
                {
                    b.HasOne("server.Models.Player", "Player")
                        .WithMany("Contracts")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("server.Models.Finance", b =>
                {
                    b.HasOne("server.Models.Team", "Team")
                        .WithMany("Finances")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("server.Models.Notification", b =>
                {
                    b.HasOne("server.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.PerformanceReport", b =>
                {
                    b.HasOne("server.Models.User", "Analyst")
                        .WithMany("PerformanceReports")
                        .HasForeignKey("AnalystId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("server.Models.Player", "Player")
                        .WithMany("PerformanceReports")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analyst");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("server.Models.Player", b =>
                {
                    b.HasOne("server.Models.User", "Agent")
                        .WithMany("Players")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("server.Models.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.HasOne("server.Models.User", "Manager")
                        .WithMany("ManagedTeams")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("server.Models.Auction", b =>
                {
                    b.Navigation("AuctionResults");

                    b.Navigation("Bids");
                });

            modelBuilder.Entity("server.Models.Player", b =>
                {
                    b.Navigation("AuctionResults");

                    b.Navigation("Contracts");

                    b.Navigation("PerformanceReports");
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Finances");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("ManagedTeams");

                    b.Navigation("Notifications");

                    b.Navigation("PerformanceReports");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
